# Generated by Django 5.1.7 on 2025-04-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='google_id',
            new_name='clerk_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
