# Generated by Django 5.1.7 on 2025-04-12 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_google_id_user_clerk_id_rename_userid_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='releaseYear',
            new_name='release_year',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='audioUrl',
            new_name='audio_url',
        ),
        migrations.RemoveField(
            model_name='album',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='album',
            name='imagineUrl',
        ),
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
        migrations.RemoveField(
            model_name='album',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='albumid',
        ),
        migrations.RemoveField(
            model_name='song',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='song',
            name='imagineUrl',
        ),
        migrations.RemoveField(
            model_name='song',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='album',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='api.album'),
        ),
        migrations.AddField(
            model_name='song',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
